flyway.url=jdbc:postgresql://localhost:5432/happyfarm?sslmode=require
flyway.user=happy
flyway.password=farm
flyway.schemas=happyfarm
flyway.defaultSchema=happyfarm
flyway.locations=filesystem:infrastructure/sql
