app {
  storage {
    connection-pool {
      min-connections = 10
      min-connections = ${?MIN_CONNECTIONS}
      max-connections = 20
      max-connections = ${?MAX_CONNECTIONS}
      timeout = 30s
    }

    database {
      host = "localhost"
      port = 5432
      dbname = "happyfarm"
      schema = "happyfarm"
      user = "happy"
      password = "farm"

      host     = ${?DB_HOST}
      port     = ${?DB_PORT}
      dbname   = ${?DB_NAME}
      schema   = ${?DB_SCHEMA}
      user     = ${?DB_USER}
      password = ${?DB_PASSWORD}
    }
  }
}