app {
  storage {
    connection-pool {
      min-connections = 10
      min-connections = ${?MIN_CONNECTIONS}
      max-connections = 20
      max-connections = ${?MAX_CONNECTIONS}
      timeout = 30s
    }

    database {
      host = "localhost"
      port = 5432
      dbname = "happyfarm"
      schema = "happyfarm"
      user = "happy"
      password = "farm"

      host     = ${?PGHOST}
      port     = ${?PGPORT}
      dbname   = ${?PGDATABASE}
      schema   = ${?PGSCHEMA}
      user     = ${?PGUSER}
      password = ${?PGPASSWORD}
    }
  }
}